// Auto-generated from devicon v3 — 578 icons
// Each entry maps a devicon base name → its best font variant suffix

const DEVICON_VARIANTS: Record<string, string> = {
  'aarch64': 'plain', 'adonisjs': 'original', 'aerospike': 'original',
  'aframe': 'plain', 'aftereffects': 'plain', 'akka': 'plain',
  'algolia': 'original', 'almalinux': 'plain', 'alpinejs': 'original',
  'amazonwebservices': 'original', 'anaconda': 'original', 'android': 'plain',
  'androidstudio': 'plain', 'angular': 'plain', 'angularjs': 'plain',
  'angularmaterial': 'plain', 'ansible': 'plain', 'ansys': 'plain',
  'antdesign': 'plain', 'apache': 'plain', 'apacheairflow': 'plain',
  'apachekafka': 'original', 'apachespark': 'original', 'apex': 'original',
  'apl': 'plain', 'apollographql': 'original', 'appcelerator': 'original',
  'apple': 'original', 'appwrite': 'original', 'archlinux': 'plain',
  'arduino': 'plain', 'argocd': 'plain', 'artixlinux': 'plain',
  'astro': 'plain', 'atom': 'original', 'awk': 'plain', 'axios': 'plain',
  'azure': 'plain', 'azuredevops': 'plain', 'azuresqldatabase': 'plain',
  'babel': 'original', 'babylonjs': 'plain', 'backbonejs': 'plain',
  'ballerina': 'original', 'bamboo': 'original', 'bash': 'plain',
  'bazel': 'plain', 'beats': 'plain', 'behance': 'plain',
  'bevyengine': 'plain', 'biome': 'original', 'bitbucket': 'original',
  'blazor': 'original', 'blender': 'original', 'bootstrap': 'plain',
  'bower': 'plain', 'browserstack': 'plain', 'bulma': 'plain',
  'bun': 'plain', 'c': 'original', 'cairo': 'plain', 'cakephp': 'plain',
  'canva': 'original', 'capacitor': 'plain', 'carbon': 'original',
  'cassandra': 'plain', 'centos': 'plain', 'ceylon': 'plain',
  'chakraui': 'plain', 'chartjs': 'plain', 'chrome': 'plain',
  'circleci': 'plain', 'clarity': 'plain', 'clickhouse': 'plain',
  'clion': 'plain', 'clojure': 'plain', 'clojurescript': 'plain',
  'cloudflare': 'plain', 'cloudflareworkers': 'plain', 'cloudrun': 'plain',
  'cmake': 'plain', 'cobol': 'original', 'codeac': 'original',
  'codecov': 'plain', 'codeigniter': 'plain', 'codepen': 'original',
  'coffeescript': 'original', 'composer': 'plain', 'confluence': 'plain',
  'consul': 'original', 'contao': 'original', 'corejs': 'original',
  'cosmosdb': 'plain', 'couchbase': 'original', 'couchdb': 'plain',
  'cpanel': 'original', 'cplusplus': 'plain', 'crystal': 'original',
  'csharp': 'plain', 'css3': 'plain', 'cucumber': 'plain',
  'cypressio': 'plain', 'd3js': 'plain', 'dart': 'plain',
  'datadog': 'original', 'datagrip': 'plain', 'dataspell': 'plain',
  'datatables': 'original', 'dbeaver': 'plain', 'debian': 'plain',
  'delphi': 'plain', 'denojs': 'original', 'detaspace': 'line',
  'devicon': 'plain', 'digitalocean': 'original', 'discloud': 'original',
  'discordjs': 'plain', 'django': 'plain', 'djangorest': 'plain',
  'docker': 'plain', 'doctrine': 'plain', 'dot-net': 'plain',
  'dotnetcore': 'plain', 'dovecot': 'plain', 'dreamweaver': 'plain',
  'dropwizard': 'plain', 'drupal': 'plain', 'duckdb': 'plain',
  'dyalog': 'plain', 'dynamodb': 'plain', 'dynatrace': 'plain',
  'eclipse': 'plain', 'ecto': 'original', 'elasticsearch': 'plain',
  'electron': 'original', 'eleventy': 'plain', 'elixir': 'plain',
  'elm': 'plain', 'emacs': 'original', 'embeddedc': 'plain',
  'ember': 'plain', 'entityframeworkcore': 'plain', 'envoy': 'plain',
  'erlang': 'plain', 'eslint': 'plain', 'expo': 'original',
  'express': 'original', 'facebook': 'original', 'fastapi': 'plain',
  'fastify': 'plain', 'faunadb': 'original', 'feathersjs': 'original',
  'fedora': 'plain', 'fiber': 'plain', 'figma': 'plain',
  'filamentphp': 'original', 'filezilla': 'plain', 'firebase': 'plain',
  'firebird': 'plain', 'firefox': 'plain', 'flask': 'original',
  'flutter': 'plain', 'forgejo': 'plain', 'fortran': 'original',
  'foundation': 'plain', 'framermotion': 'original', 'framework7': 'original',
  'fsharp': 'plain', 'fusion': 'plain', 'gardener': 'plain',
  'gatling': 'original', 'gatsby': 'original', 'gazebo': 'plain',
  'gcc': 'plain', 'gentoo': 'plain', 'ghost': 'original',
  'gimp': 'plain', 'git': 'plain', 'gitbook': 'original',
  'github': 'original', 'githubactions': 'plain', 'githubcodespaces': 'plain',
  'gitkraken': 'original', 'gitlab': 'plain', 'gitpod': 'plain',
  'gitter': 'plain', 'gleam': 'plain', 'glitch': 'plain',
  'go': 'plain', 'godot': 'plain', 'goland': 'plain',
  'google': 'original', 'googlecloud': 'plain', 'googlecolab': 'plain',
  'gradle': 'original', 'grafana': 'plain', 'grails': 'plain',
  'graphql': 'plain', 'groovy': 'plain', 'grpc': 'plain',
  'grunt': 'plain', 'gulp': 'plain', 'hadoop': 'plain',
  'handlebars': 'original', 'harbor': 'plain', 'hardhat': 'plain',
  'harvester': 'original', 'haskell': 'plain', 'haxe': 'plain',
  'helm': 'original', 'heroku': 'original', 'hibernate': 'plain',
  'homebrew': 'plain', 'hoppscotch': 'plain', 'html5': 'plain',
  'htmx': 'plain', 'hugo': 'plain', 'hyperv': 'plain',
  'ie10': 'original', 'ifttt': 'original', 'illustrator': 'plain',
  'inertiajs': 'plain', 'influxdb': 'original', 'inkscape': 'plain',
  'insomnia': 'plain', 'intellij': 'plain', 'ionic': 'original',
  'jaegertracing': 'plain', 'jamstack': 'original', 'jasmine': 'original',
  'java': 'plain', 'javascript': 'plain', 'jeet': 'plain',
  'jekyll': 'plain', 'jenkins': 'plain', 'jest': 'plain',
  'jetbrains': 'plain', 'jetpackcompose': 'plain', 'jhipster': 'plain',
  'jira': 'plain', 'jiraalign': 'plain', 'jquery': 'plain',
  'json': 'plain', 'jule': 'original', 'julia': 'plain',
  'junit': 'plain', 'jupyter': 'plain', 'k3os': 'original',
  'k3s': 'original', 'k6': 'original', 'kaggle': 'original',
  'kaldi': 'plain', 'kalilinux': 'original', 'karatelabs': 'plain',
  'karma': 'plain', 'kdeneon': 'plain', 'keras': 'plain',
  'kibana': 'plain', 'knexjs': 'original', 'knockout': 'plain-wordmark',
  'kotlin': 'plain', 'krakenjs': 'plain', 'ktor': 'plain',
  'kubeflow': 'plain', 'kubernetes': 'plain', 'labview': 'plain',
  'laminas': 'original', 'laravel': 'original', 'laraveljetstream': 'original',
  'latex': 'original', 'leetcode': 'plain', 'less': 'plain-wordmark',
  'libgdx': 'plain', 'linkedin': 'plain', 'linux': 'plain',
  'linuxmint': 'plain', 'liquibase': 'original', 'livewire': 'plain',
  'llvm': 'plain', 'lodash': 'plain', 'logstash': 'plain',
  'love2d': 'plain', 'lua': 'plain', 'lumen': 'original',
  'magento': 'original', 'mapbox': 'original', 'mariadb': 'original',
  'markdown': 'original', 'materializecss': 'plain', 'materialui': 'plain',
  'matlab': 'plain', 'matplotlib': 'plain', 'mattermost': 'original',
  'maven': 'plain', 'maya': 'plain', 'memcached': 'plain',
  'mercurial': 'plain', 'meteor': 'plain', 'microsoftsqlserver': 'plain',
  'minitab': 'plain', 'mithril': 'original', 'mobx': 'plain',
  'mocha': 'plain', 'modx': 'plain', 'moleculer': 'original',
  'mongodb': 'plain', 'mongoose': 'original', 'monogame': 'original',
  'moodle': 'plain', 'msdos': 'plain', 'mysql': 'original',
  'nano': 'plain', 'nats': 'plain', 'neo4j': 'plain',
  'neovim': 'plain', 'nestjs': 'original', 'netbeans': 'plain',
  'netbox': 'plain', 'netlify': 'plain', 'networkx': 'plain',
  'newrelic': 'plain', 'nextjs': 'plain', 'nginx': 'original',
  'ngrok': 'original', 'ngrx': 'plain', 'nhibernate': 'plain',
  'nim': 'plain', 'nimble': 'plain', 'nixos': 'plain',
  'nodejs': 'plain', 'nodemon': 'plain', 'nodered': 'plain',
  'nodewebkit': 'plain', 'nomad': 'original', 'norg': 'plain',
  'notion': 'plain', 'npm': 'plain', 'npss': 'plain',
  'nuget': 'original', 'numpy': 'plain', 'nuxt': 'original',
  'nuxtjs': 'plain', 'oauth': 'plain', 'objectivec': 'plain',
  'ocaml': 'plain', 'ohmyzsh': 'plain', 'okta': 'plain',
  'openal': 'plain', 'openapi': 'plain', 'opencl': 'plain',
  'opencv': 'plain', 'opengl': 'plain', 'openstack': 'original',
  'opensuse': 'original', 'opentelemetry': 'plain', 'opera': 'plain',
  'oracle': 'original', 'ory': 'original', 'p5js': 'original',
  'packer': 'plain', 'pandas': 'plain', 'passport': 'plain',
  'perl': 'plain', 'pfsense': 'original', 'phalcon': 'plain',
  'phoenix': 'original', 'photonengine': 'plain', 'photoshop': 'plain',
  'php': 'plain', 'phpstorm': 'plain', 'pixijs': 'plain',
  'playwright': 'plain', 'plotly': 'plain', 'pm2': 'plain',
  'pnpm': 'plain', 'podman': 'plain', 'poetry': 'plain',
  'polygon': 'plain', 'portainer': 'original', 'postcss': 'original',
  'postgresql': 'plain', 'postman': 'plain', 'powershell': 'plain',
  'premierepro': 'plain', 'primeng': 'plain', 'prisma': 'original',
  'processing': 'plain', 'processwire': 'original', 'prolog': 'plain',
  'prometheus': 'original', 'protractor': 'plain', 'proxmox': 'plain',
  'pug': 'plain', 'pulsar': 'original', 'pulumi': 'plain',
  'puppeteer': 'plain', 'purescript': 'original', 'putty': 'plain',
  'pycharm': 'plain', 'pypi': 'plain', 'pyscript': 'plain-wordmark',
  'pytest': 'plain', 'python': 'plain', 'pytorch': 'original',
  'qodana': 'plain', 'qt': 'original', 'qtest': 'original',
  'quarkus': 'plain', 'quasar': 'plain', 'qwik': 'plain',
  'r': 'plain', 'rabbitmq': 'original', 'racket': 'plain',
  'radstudio': 'plain', 'rails': 'plain', 'railway': 'original',
  'rancher': 'original', 'raspberrypi': 'plain', 'reach': 'plain',
  'react': 'original', 'reactbootstrap': 'original', 'reactnative': 'original',
  'reactnavigation': 'original', 'reactrouter': 'plain', 'readthedocs': 'original',
  'realm': 'plain', 'rect': 'plain', 'redhat': 'plain',
  'redis': 'plain', 'redux': 'original', 'reflex': 'plain',
  'remix': 'original', 'renpy': 'plain', 'replit': 'original',
  'rexx': 'plain', 'rider': 'plain', 'rocksdb': 'plain',
  'rockylinux': 'original', 'rollup': 'plain', 'ros': 'original',
  'rspec': 'plain', 'rstudio': 'plain', 'ruby': 'plain',
  'rubymine': 'plain', 'rust': 'original', 'rxjs': 'plain',
  'safari': 'plain', 'salesforce': 'plain', 'sanity': 'plain',
  'sass': 'original', 'scala': 'plain', 'scalingo': 'plain',
  'scikitlearn': 'plain', 'sdl': 'plain', 'selenium': 'original',
  'sema': 'original', 'sentry': 'original', 'sequelize': 'plain',
  'shopware': 'original', 'shotgrid': 'plain', 'sketch': 'plain',
  'slack': 'plain', 'socketio': 'original', 'solidity': 'plain',
  'solidjs': 'plain', 'sonarqube': 'original', 'sourceengine': 'plain',
  'sourcetree': 'original', 'spack': 'plain', 'spicedb': 'plain',
  'splunk': 'original-wordmark', 'spring': 'original', 'spss': 'plain',
  'spyder': 'plain', 'sqlalchemy': 'plain', 'sqldeveloper': 'plain',
  'sqlite': 'plain', 'ssh': 'original', 'stackblitz': 'original',
  'stackoverflow': 'plain', 'stata': 'original-wordmark',
  'stenciljs': 'plain', 'storybook': 'plain', 'streamlit': 'plain',
  'styledcomponents': 'plain', 'stylus': 'original', 'subversion': 'original',
  'sulu': 'original', 'supabase': 'plain', 'surrealdb': 'plain',
  'svelte': 'plain', 'svgo': 'plain', 'swagger': 'plain',
  'swift': 'plain', 'swiper': 'original', 'symfony': 'original',
  'tailwindcss': 'original', 'talos': 'plain', 'tauri': 'plain',
  'teleport': 'original', 'tensorflow': 'original', 'terraform': 'plain',
  'terramate': 'original', 'tex': 'original', 'thealgorithms': 'plain',
  'threedsmax': 'plain', 'threejs': 'original', 'thymeleaf': 'plain',
  'titaniumsdk': 'original', 'tmux': 'plain', 'tomcat': 'line',
  'tortoisegit': 'plain', 'towergit': 'plain', 'traefikmesh': 'original',
  'traefikproxy': 'original', 'travis': 'plain', 'trello': 'plain',
  'trpc': 'plain', 'turbo': 'original', 'twilio': 'original',
  'twitter': 'original', 'typescript': 'original', 'typo3': 'original',
  'ubuntu': 'plain', 'unifiedmodelinglanguage': 'plain', 'unity': 'plain',
  'unix': 'original', 'unrealengine': 'original', 'uwsgi': 'plain',
  'v8': 'plain', 'vaadin': 'original', 'vagrant': 'plain',
  'vala': 'plain', 'vault': 'original', 'veevalidate': 'original',
  'vercel': 'original', 'vertx': 'plain', 'vim': 'plain',
  'visualbasic': 'plain', 'visualstudio': 'plain', 'vite': 'original',
  'vitejs': 'plain', 'vitess': 'plain', 'vitest': 'plain',
  'vscode': 'plain', 'vscodium': 'plain', 'vsphere': 'plain',
  'vuejs': 'plain', 'vuestorefront': 'plain', 'vuetify': 'plain',
  'vulkan': 'original', 'vyper': 'original', 'waku': 'plain',
  'wasm': 'original', 'web3js': 'plain', 'webflow': 'original',
  'webgpu': 'plain', 'weblate': 'plain', 'webpack': 'plain',
  'webstorm': 'plain', 'windows11': 'original', 'windows8': 'original',
  'wolfram': 'plain', 'woocommerce': 'plain', 'wordpress': 'plain',
  'xamarin': 'original', 'xcode': 'plain', 'xd': 'plain',
  'xml': 'plain', 'yaml': 'plain', 'yarn': 'original',
  'yii': 'plain', 'yugabytedb': 'plain', 'yunohost': 'plain',
  'zend': 'original', 'zig': 'original', 'zsh': 'plain',
  'zustand': 'plain',
}

// Explicit aliases: GitHub language name → devicon base name
const ALIASES: Record<string, string> = {
  'c++': 'cplusplus',
  'c#': 'csharp',
  'f#': 'fsharp',
  'html': 'html5',
  'css': 'css3',
  'shell': 'bash',
  'objective-c': 'objectivec',
  'objectivec': 'objectivec',
  'node': 'nodejs',
  'node.js': 'nodejs',
  'vue': 'vuejs',
  'vue.js': 'vuejs',
  'react': 'react',
  'angular': 'angular',
  '.net': 'dotnetcore',
  'dotnet': 'dotnetcore',
  'sass': 'sass',
  'dockerfile': 'docker',
  'viml': 'vim',
  'vim script': 'vim',
  'emacs lisp': 'emacs',
  'jupyter notebook': 'jupyter',
  'tex': 'latex',
  'latex': 'latex',
  'crystal': 'crystal',
  'nim': 'nim',
  'zig': 'zig',
  'solidity': 'solidity',
  'vyper': 'vyper',
  'purescript': 'purescript',
  'nix': 'nixos',
  'processing': 'processing',
  'maxscript': 'threedsmax',
  'gdc': 'gcc',
  'gdscript': 'godot',
  'cmake': 'cmake',
  'makefile': 'linux',
  'asp.net': 'dotnetcore',
  'blazor': 'blazor',
  'elixir': 'elixir',
  'elm': 'elm',
  'erlang': 'erlang',
  'gleam': 'gleam',
  'haskell': 'haskell',
  'haxe': 'haxe',
  'julia': 'julia',
  'kotlin': 'kotlin',
  'lua': 'lua',
  'ocaml': 'ocaml',
  'perl': 'perl',
  'php': 'php',
  'python': 'python',
  'r': 'r',
  'ruby': 'ruby',
  'rust': 'rust',
  'scala': 'scala',
  'swift': 'swift',
  'typescript': 'typescript',
  'javascript': 'javascript',
  'go': 'go',
  'java': 'java',
  'dart': 'dart',
  'clojure': 'clojure',
  'groovy': 'groovy',
  'racket': 'racket',
}

// Precompute normalized name set for fast lookup
const DEVICON_NAMES = new Set(Object.keys(DEVICON_VARIANTS))

function normalize(name: string): string {
  return name
    .toLowerCase()
    .replace(/[.+#\s-]/g, '')
}

export function langIcon(lang: string | null): string {
  if (!lang) return ''
  const lower = lang.toLowerCase()

  // 1. Direct alias match
  if (ALIASES[lower]) {
    const base = ALIASES[lower]
    const variant = DEVICON_VARIANTS[base]
    return `devicon-${base}-${variant}`
  }

  // 2. Already a devicon name
  if (DEVICON_NAMES.has(lower)) {
    const variant = DEVICON_VARIANTS[lower]
    return `devicon-${lower}-${variant}`
  }

  // 3. Normalize and try
  const norm = normalize(lang)
  if (DEVICON_NAMES.has(norm)) {
    const variant = DEVICON_VARIANTS[norm]
    return `devicon-${norm}-${variant}`
  }

  // 4. Try common transforms
  const transforms = [
    lower.replace(/\s+/g, ''),
    lower.replace(/[+#]/g, 'plus'),
    lower.replace(/\./g, ''),
    lower.replace(/-/g, ''),
    lower.replace(/^\./, ''),
    norm + 'js',
    norm.replace(/^jquery/, 'jquery'),
    'devicon-' + norm,
  ]
  for (const t of transforms) {
    if (DEVICON_NAMES.has(t)) {
      const variant = DEVICON_VARIANTS[t]
      return `devicon-${t}-${variant}`
    }
  }

  return ''
}
